version: '3.7'

services:
    berivo_v2_host_db:
        container_name: 'db_berivo_v2'
        image: 'postgres:14-alpine'
        restart: always
        env_file:
            - ./.env
        ports:
            - '5435:5432'
        volumes:
            - ./database/dbberivov2develop:/var/lib/postgresql/data/

    berivo_v2_api:
        container_name: 'berivo_v2_api'
        build: .
        restart: always
        volumes:
            - .:/app/
            - /app/node_modules
        entrypoint: /bin/sh './scripts/be-node-dev.sh'
        env_file:
            - ./.env
        ports:
            - '3000:3000'
        depends_on:
            - berivo_v2_host_db
        links:
            - berivo_v2_host_db